/* tslint:disable */

/**
 * The data type for the custom field
 * Possible values are:
 * - `boolean`: A boolean value
 * - `date`: A date value
 * - `decimal`: A decimal value
 * - `dynamicSelection`: Single selection based on options generated by a custom script
 * - `file`: Multiple binary files
 * - `image`: Multiple images
 * - `integer`: An integer value
 * - `linkedEntity`: Another entity. Uses the `linkedEntityType` to define which kind of entity is it
 * - `multiSelection`: Multiple enumerated values
 * - `richText`: A multi line string formatted as HTML
 * - `singleSelection`: A single enumerated value
 * - `string`: A single line string
 * - `text`: A multi line string
 * - `url`: An URL
 */
export enum CustomFieldTypeEnum {
  BOOLEAN = 'boolean',
  DATE = 'date',
  DECIMAL = 'decimal',
  DYNAMIC_SELECTION = 'dynamicSelection',
  FILE = 'file',
  IMAGE = 'image',
  INTEGER = 'integer',
  LINKED_ENTITY = 'linkedEntity',
  MULTI_SELECTION = 'multiSelection',
  RICH_TEXT = 'richText',
  SINGLE_SELECTION = 'singleSelection',
  STRING = 'string',
  TEXT = 'text',
  URL = 'url'
}
