/* tslint:disable */
import { AccountHistoryQueryFilters } from './account-history-query-filters';
import { AccountWithOwnerAndCurrency } from './account-with-owner-and-currency';
import { BaseTransferDataForSearch } from './base-transfer-data-for-search';
import { CustomField } from './custom-field';
import { CustomFieldDetailed } from './custom-field-detailed';
import { EntityReference } from './entity-reference';
import { User } from './user';

/**
 * Contains data used to search the history of a given account
 */
export interface DataForAccountHistory extends BaseTransferDataForSearch {

  /**
   * References for access clients which can be used to filter entries by transfers generated by a specific access client
   */
  accessClients?: Array<EntityReference>;
  account?: AccountWithOwnerAndCurrency;

  /**
   * Whether the current user can use the direction filter by direction. In some cases, such as restricted operators that can only see incoming or outgoing payments, this flag will be `false`.
   */
  canFilterByDirection?: boolean;

  /**
   * Simple references for custom fields that are set to be used on the search result list
   */
  customFieldsInList?: Array<CustomField>;

  /**
   * Detailed references for custom fields that are set to be used as search filters
   */
  customFieldsInSearch?: Array<CustomFieldDetailed>;

  /**
   * References for operators, which can be used to filter entries by transfers performed or received by that specific operator
   */
  operators?: Array<User>;

  /**
   * Default query filters for the account history
   */
  query?: AccountHistoryQueryFilters;

  /**
   * Whether to show the description as filter or not
   */
  showDescriptionInFilters?: boolean;

  /**
   * Whether to show the description in the result list or not
   */
  showDescriptionInList?: boolean;

  /**
   * If a transaction number is used for this account, is a pattern that represent it.
   */
  transactionNumberMask?: string;
}
