/* tslint:disable */
import { InternalNamedEntity } from './internal-named-entity';

/**
 * Contains a reference to an export format
 */
export interface ExportFormat extends InternalNamedEntity {

  /**
   * Indicates whether the content generated by this format is binary (true) or textual (false)
   */
  binary?: boolean;

  /**
   * Indicates the content type (mime type) for the generated content.
   */
  contentType?: string;

  /**
   * Indicates the character encoding for the textual content. Only returned `binary` is false.
   */
  encoding?: string;
}
