/* tslint:disable */
import { NfcTokenParameter } from './nfc-token-parameter';

/**
 * Parameters for personalizing an NFC tag for a new user
 */
export interface NfcTokenWithChallengeParameter extends NfcTokenParameter {

  /**
   * The challenge that was previously generated by Cyclos, encrypted by the NFC tag. Encoded as hex.
   */
  cyclosChallenge?: string;
}
