/* tslint:disable */
import { BaseTransactionDataForSearch } from './base-transaction-data-for-search';
import { EntityReference } from './entity-reference';
import { TransactionQueryFilters } from './transaction-query-filters';
import { User } from './user';

/**
 * Contains data used to search transactions for a given owner
 */
export interface TransactionDataForSearch extends BaseTransactionDataForSearch {

  /**
   * References for access clients which can be used to filter entries by transfers generated by a specific access client
   */
  accessClients?: Array<EntityReference>;

  /**
   * References for operators, which can be used to filter entries by transfers performed or received by that specific operator
   */
  operators?: Array<User>;

  /**
   * Default query filters for the transactions search
   */
  query?: TransactionQueryFilters;

  /**
   * When the given owner is a user, is the reference to it
   */
  user?: User;
}
