/* tslint:disable */

/**
 * Indicates how a voucher was created
 * Possible values are:
 * - `bought`: The voucher was bought by an user
 * - `generated`: The voucher was generated by an administrator
 */
export enum VoucherCreationTypeEnum {
  BOUGHT = 'bought',
  GENERATED = 'generated'
}
